### ISSUE TITLE
Wrong PyPi Link in Docs

### ISSUE THREAD

**Issue by Nickwasused** [Nevalicjus/ntfpy#2]
## Expected Behaviour
The PyPi Url should redirect to the correct Project Page.

## Observed Behaviour
The Url is wrong.

## Steps to reproduce
1. Go to: `https://docs.n3v.xyz/ntfpy/`
2. Click on: `https://pypi.org/projects/ntfpy`
3. Get a 404

## Context (Environment)
`https://docs.n3v.xyz/ntfpy/`

## Possible Solution
Change the Url from `https://pypi.org/projects/ntfpy` to `https://pypi.org/project/ntfpy`. (Notice the removed `s`)

**Comment by Nevalicjus** [comment]
Thanks for noticing, should be fixed now:)

Actually, that documentation is slightly outdated, it'd be better to use `https://ntfpy.nevdocs.xyz`, which might still be worked on but is up to date 😅
